BookingApp/Areas/Authentication/Controllers/AuthenticationController.cs
using Microsoft.Owin.Security;
using Models;
using System;
using System.Web;
using System.Web.Mvc;
using Common.Database;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using BookingApp.Models;

namespace BookingApp.Areas.Authentication.Controllers
{
    public class AuthenticationController : Controller
    {
        private IAuthenticationManager AuthenticationManager { get { return HttpContext.GetOwinContext().Authentication; } }

        //[AllowAnonymous]
        //public ActionResult Login()
        //{
        //    if (User.Identity.IsAuthenticated)
        //    {
        //        //if (bool.Parse(ApplicationUser.getPropertyValue("SuperUser")) == true)
        //        //    return RedirectToAction("Analytics", "Dashboard", new { area = "Dashboard" });
        //        //else
        //        //    return RedirectToAction("MyProfile", "Profiles", new { area = "Profiles" });

        //        return RedirectToAction("Dashboard", "Dashboard", new { area = "Dashboard" });
        //    }

        //    LoginModel model = new LoginModel();

        //    return View(model);
        //}


        [AllowAnonymous]
        public ActionResult Login(string recentlySignedUp)
        {
            if (string.IsNullOrEmpty(recentlySignedUp))
            {
                if (User.Identity.IsAuthenticated)
                    return RedirectToAction("Dashboard", "Dashboard", new { area = "Dashboard" });

                LoginModel model = new LoginModel();

                return View(model);
            }
            else {
                LoginModel model = new LoginModel { RecentlySignedUp = "True" };

                return View(model);
            }
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Please enter your credentials");
                return View(model);
            }

            user user = Common.User.login(model.Username, model.Password);

            if (user == null)
            {
                //return that it failed
                model.Failed = true;
                return View(model);
            }

            //Log them in
            //create the custom application user
            var userClaim = new ApplicationUser()
            {
                Id = user.id.ToString(),
                UserName = user.username,
                Guid = user.guid,
                UserID = user.id,
                FirstName = user.name,
                LastName = user.surname,
                FullName = $"{user.name} {user.surname}",
                Email = user.email,
                SuperUser = user.superUser == true,
                Password = user.password,
                StudioId = (int)user.studio_id,
                Marshal = user.marshal == true,
                SecurityStamp = Guid.NewGuid().ToString(),
            };

            //CustomUserManager userManager = HttpContext.GetOwinContext().GetUserManager<CustomUserManager>();
            CustomUserManager userManager = new CustomUserManager();

            //create the user identity which will be stored in the httpcontext.current.user property going forward
            ClaimsIdentity identity = userManager.CreateIdentity(userClaim, DefaultAuthenticationTypes.ApplicationCookie);

            //add each custom property as a claim so we can access it once the user is logged in (without pulling it from the db)
            identity.AddClaims(ApplicationUser.populateClaims(userClaim));

            AuthenticationProperties authProperties = new AuthenticationProperties();
            authProperties.ExpiresUtc = DateTime.UtcNow.AddDays(!model.RememberMe ? 3 : 45);

            //sign the user in
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            AuthenticationManager.SignIn(authProperties, identity);

            //FormsAuthentication.SetAuthCookie(ApplicationUser.getPropertyValue("id").ToString(), false);

            userManager.Dispose();

            //if (user.superUser == true)
            //    return RedirectToAction("Analytics", "Dashboard", new { area = "Dashboard" });
            //else
                return RedirectToAction("Dashboard", "Dashboard", new { area = "Dashboard" });

        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Login");
        }


        [AllowAnonymous]
        public ActionResult Register(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Login");

            StudioModel studioModel = StudioModel.getStudio(id);

            if (studioModel == null)
                return RedirectToAction("Login");

            UserModel model = new UserModel { Guid = studioModel.Guid, StudioName = studioModel.Name, StudioId = studioModel.StudioId, SuperUser = false };

            return View(model);
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserModel model)
        {
            //if (!Common.Studio.incrementMemberCount(model.StudioId))
            //{
            //    //return failed message - too full
            //}

            int newUserId = Common.User.addUser(model.Name, model.Surname, model.UserName, model.Password, model.Email, false, model.StudioId, model.ContactNumber);

            return RedirectToAction("Login", new { recentlySignedUp = "True" });
        }


    }
}

BookingApp/Areas/Authentication/Views/Authentication/Login.cshtml
@using Models;
@model LoginModel

@{
    ViewBag.Title = "User Login";
    Layout = "~/Views/Shared/_AuthenticationLayout.cshtml";
}

<head>
    <script>
        addToHomescreen({
            skipFirstVisit: true,
            maxDisplayCount: 1
        });
    </script>
</head>

    <div class="user-login-5">
        <div class="row bs-reset">


            <div style="display: table;position: absolute;height: 100%;width: 100%;">
                <div style="display: table-cell;vertical-align: middle;">
                    <div style="margin-left: auto;margin-right: auto; ">

                        <div class="col-md-12 col-xs-12 login-container bs-reset">
                            <div style="text-align:center">
                                <img src="@Url.Content("~/Content/img/logo.png")" style="max-width:80%; position:inherit" />
                            </div>
                            <div class="login-content">

                                @using (Html.BeginForm("Login", "Authentication", null, FormMethod.Post, new { @class = "login-form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.HiddenFor(m => m.RememberMe)
                                    <div class="alert alert-danger display-hide">
                                        <button class="close" data-close="alert"></button>
                                        <span>Enter any username and password. </span>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-6">
                                            @Html.TextBoxFor(m => m.Username, new { placeholder = "Username Or Email", @class = "form-control form-control-solid placeholder-no-fix form-group", type = "text", autocomplete = "off", name = "username", required = true })
                                        </div>
                                        <div class="col-xs-6">
                                            @Html.TextBoxFor(m => m.Password, new { placeholder = "Password", @class = "form-control form-control-solid placeholder-no-fix form-group", type = "password", autocomplete = "off", name = "password", required = true })
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-8 col-xs-8">
                                            <label class="rememberme mt-checkbox mt-checkbox-outline">
                                                <input type="checkbox" name="remember" id="remCheck" value="1" onchange="updateRememberMe()" /> Remember me
                                                <span></span>
                                            </label>
                                        </div>
                                        <div class="col-sm-4 col-xs-4 text-right">
                                            <button class="btn blue" type="submit" style="float:right">Sign In</button>
                                        </div>
                                    </div>
                                    <div class="row" style="text-align:center">
                                        <br /><br />
                                        <div class="forgot-password">
                                            <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>
                                        </div>
                                    </div>
                                }


                                <!-- BEGIN FORGOT PASSWORD FORM -->
                                <form class="forget-form" action="javascript:;" method="post">
                                    <h3>Forgot Password ?</h3>
                                    <p> Enter your e-mail address below to reset your password. </p>
                                    <div class="form-group">
                                        <input id="emailInput" class="form-control form-control-solid placeholder-no-fix form-group" type="email" autocomplete="off" placeholder="Email" name="email" required />
                                    </div>
                                    <div class="form-actions">
                                        <button type="button" id="back-btn" class="btn blue btn-outline">Back</button>
                                        <button type="submit" class="btn blue pull-right" onclick="submitEmail()">Submit</button>
                                    </div>
                                </form>
                                <!-- END FORGOT PASSWORD FORM -->
                            </div>
                        </div>

                    </div>
                </div>
            </div>













            @*<div class="col-md-6 bs-reset">
                <div class="login-bg"> </div>
            </div>*@
        </div>
    </div>

  <script>

        $(document).ready(function () {
   
            if ("@Model.RecentlySignedUp" == "True") {
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "positionClass": "toast-top-center",
                    "onclick": null,
                    "showDuration": "2000",
                    "hideDuration": "2000",
                    "timeOut": "5000",
                    "extendedTimeOut": "2000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                };
                toastr.success('Login to start your booking experience', 'Successful!');
            }

            else if ("@Model.Failed" == "True") {
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "positionClass": "toast-top-center",
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                };
                toastr.error('Incorrect Username and Password combination. Please try again.', 'Sorry...');
                $('#Username').val("");
                $('#Password').val("");
        }
      });


      function updateRememberMe() {
          if ($('#remCheck')[0].checked) {
              $('#RememberMe').val(true);
          }
          else {
              $('#RememberMe').val(false);
          }
      }

      function submitEmail() {
          debugger;
          if ($('#emailInput')[0].checkValidity()) {
              swal("Email Sent!", "Follow the link in the email to reset your password", "success");
              $('#emailInput').val("");
          }
      }

    </script>

BookingApp/Areas/Authentication/Views/Authentication/Register.cshtml
@using Models;
@model UserModel

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_AuthenticationLayout.cshtml";
}

<div class="user-login-5">
    <div class="row bs-reset">
        <div class="col-md-6 login-container bs-reset">
            <img class="login-logo login-6" src="@Url.Content("~/Content/img/login-invert.png")" />
            <div class="login-content" style="margin-top:30%">
                <h1>Marshal Register</h1>
                <h3>@Model.StudioName</h3>


                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
@using (Html.BeginForm("Register", "Authentication", null, FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Guid)
    @Html.HiddenFor(m => m.SuperUser)
    @Html.HiddenFor(m => m.StudioId)

                        <div class="form-body">
                            <br /><br />
                            <div class="form-group">
                                <label class="col-md-3 control-label" style="text-align:left">First Name</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", type = "text", required = true })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" style="text-align:left">Last Name</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", type = "text", required = true })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" style="text-align:left">Email Address</label>
                                <div class="col-md-9">
                                    <div class="input-icon right">
                                        <i class="fa fa-envelope"></i>
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", type = "email", required = true })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" style="text-align:left">Contact #</label>
                                <div class="col-md-9">
                                    <div class="input-icon right">
                                        <i class="fa fa-phone"></i>
                                        @Html.TextBoxFor(m => m.ContactNumber, new { @class = "form-control", type = "tel", required = true })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" style="text-align:left">Username</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", type = "text", required = true })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" style="text-align:left">Password</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control", type = "password", required = true })
                                </div>
                            </div>
                        </div>
                    
                    <button type="submit" class="btn blue">Submit</button>
                    }
                    <!-- END FORM-->
                </div>

            </div>
        </div>
        <div class="col-md-6 bs-reset">
            <div class="login-bg"> </div>
        </div>
    </div>
</div>